version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendLMH
    container_name: frontendLMH
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebLMH

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendLMH
    container_name: backendLMH
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebLMH

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebLMH
    container_name: webLMH
    ports:
      - "8080:80" # Si tienes problemas con el puerto 80, cámbialo aquí
    networks:
      - redwebLMH

networks:
  redwebLMH:
    driver: bridge

